name: staticcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: staticcheck
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
        id: go

      - name: install staticcheck
        run: |
          cd /tmp && go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: make staticcheck
        env:
          GOFLAGS: -mod=vendor
        run: |
          make staticcheck
